## **SQL** - Structured Query Language is the language( commands )

## **SQLite, MySQL, PostgreSQL, and Oracle** are database systems that store data and execute SQL commands.



> SQLite3 = Python's simplest database system that stores data in a .db file and executes SQL commands.


> sqlite3 is Python's module (library) for talking to SQLite database.

# **BASICS**

In [1]:
import sqlite3 # The sqlite3 module comes pre-installed with Python, so no pip install is needed.
import pandas as pd

# **Step 1 : Connect**

In [2]:
conn = sqlite3.connect('company.db')

# **Step 2 : Create a table**

In [3]:
conn.execute("CREATE TABLE Employees(id INTEGER, name TEXT, salary INTEGER)")

# **Step 3 : Insert Values**

In [4]:
conn.execute("""
    INSERT INTO Employees VALUES(1,'vamshi',30000),(2,'Abhi',28000),(3,'Varshith',50000)
""")

# **Step 4 : Save Changes**
### Use commit after:

### CREATE, INSERT, UPDATE, DELETE

In [5]:
conn.commit()

# **Step 5 : Read data back**
## To Display rows using Pandas DataFrame

In [6]:
df = pd.read_sql_query("SELECT * FROM EMPLOYEES",conn)

In [7]:
df

   id      name  salary
0   1    vamshi   30000
1   2      Abhi   28000
2   3  Varshith   50000

## **Display Rows Without DataFrame**

In [8]:
conn.execute('SELECT * FROM Employees') # runs the query, but it does not display the results.

In [9]:
cursor = conn.execute("SELECT * FROM Employees")
for row in cursor:
  print(row)

(1, 'vamshi', 30000)
(2, 'Abhi', 28000)
(3, 'Varshith', 50000)

## **fetchone()** - Gets one row at a time.
## **fetchall()** - Gets all remaining rows.
## **fetchmany()** - Gets a specific number of rows.

In [10]:
cursor = conn.execute("SELECT * FROM Employees;")

In [11]:
# fetchone()
row = cursor.fetchone()
print(row)

(1, 'vamshi', 30000)

In [12]:
# Calling fetchone() Again - Cursor remembers its position.
row = cursor.fetchone()
print(row)

(2, 'Abhi', 28000)

In [13]:
cursor = conn.execute("SELECT * FROM Employees")

In [14]:
# fetchmany()
rows = cursor.fetchmany(2)
print(rows) # returns list of rows

[(1, 'vamshi', 30000), (2, 'Abhi', 28000)]

In [15]:
# fetchall()
r = cursor.fetchall()
print(r)

[(3, 'Varshith', 50000)]

# **Parameterized Queries (? Placeholders)**

In [16]:
conn.execute("CREATE TABLE tutorial(name TEXT,age INTEGER)")

In [17]:
# When inserting values from Python, don't build SQL strings manually. - works but not a good practice
name = 'vamshi'
age = 22
conn.execute(f"INSERT INTO tutorial VALUES('{name}',{age})")

In [18]:
# Use ? Placeholders
name = 'dunna'
age = 16
conn.execute("INSERT INTO tutorial VALUES(?,?)",(name,age))

In [19]:
df = pd.read_sql_query("SELECT * FROM tutorial" ,conn)
df

     name  age
0  vamshi   22
1   dunna   16

In [20]:
# using placeholders in where clause
age = 20
df = pd.read_sql_query("SELECT * FROM tutorial WHERE age > ?",conn,params=(age,)) #The comma is important.
# A single-value tuple in Python needs a trailing comma, so (age,) written.
df

     name  age
0  vamshi   22

# **Write DataFrame to SQLite**

In [21]:
df = pd.DataFrame({'ID':[1,2,3],'SALARY':[10000,45000,25000],'DEPT':['SC','HR','IT']})
df

   ID  SALARY DEPT
0   1   10000   SC
1   2   45000   HR
2   3   25000   IT

### Meaning of parameters used in df.to_sql()
### if_exists="replace" - Delete old table and create new one.
### if_exists="append" - Add rows to existing table.
### index=False - Don't save Pandas index as a column.

In [22]:
#### df.to_sql()
df.to_sql("salary",conn,if_exists="replace",index=False)

3

In [23]:
c = conn.execute("SELECT * FROM salary")
for row in c:
  print(row)

(1, 10000, 'SC')
(2, 45000, 'HR')
(3, 25000, 'IT')

# **Close Connection**
## It is a good practice to close database connection after use

In [24]:
conn.close()

In [25]:
conn.execute("SELECT * FROM Employees") # o/p : cannot operate on a closed database

ProgrammingError: Cannot operate on a closed database.

# **REMEMBER THESE :**
### conn = sqlite3.connect('databsename.db')
### conn.execute()
### conn.commit()
### df = pd.read_sql_query()
### df.to_sql()
### conn.close()